version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp-fpm
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wp-data:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: wp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wp-data:/var/www/html
    depends_on:
      - wordpress

  db:
    image: mariadb:10.6
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: wp-adminer
    ports:
      - "8081:8080"
    volumes:
      # Usa la ruta relativa a tu archivo docker-compose.yml
      - ./adminer-theme/adminer.css:/var/www/html/adminer.css
    depends_on:
      - db
volumes:
  db_data: